site_name: http4k Connect
site_url: https://connect.http4k.org/
site_description: http4k Connect is a lightweight API client toolkit which includes libraries for connecting to popular third-party cloud services and AI backends
site_author: David Denton (@daviddenton), Ivan Sanchez (@s4nchez)
copyright: 'Copyright &copy; 2024 - David Denton (@daviddenton), IvanSanchez (@s4nchez)'
remote_branch: master
repo_url: https://github.com/http4k/http4k-connect/
theme:
  name: 'material'
  custom_dir: ./docs/theme
  static_templates:
      - ./index.html
  palette:
    primary: 'indigo'
    accent: 'blue'
  logo: img/logo_1100x200_white_on_blue_trans.png
google_analytics: ['UA-125143867-1', 'auto']
markdown_extensions:
  - meta
  - codehilite
  - toc:
      permalink: True
      separator: "_"
extra_css:
  - ./css/site.css
extra:
  logo: img/logo_1100x200_white_on_blue_trans.png
edit_uri: edit/master/src/docs/
strict: false
