@startuml
title RenderingTest - render successful trace
participant "user"
participant "internal1"
participant "internal2"
participant "external1"
participant "external2"
"user" -> "internal1": GET int1
activate "internal1"
"internal1" -> "external1": GET ext1
activate "external1"

"external1" -[#DarkGreen]> "internal1": <color:DarkGreen> 200 OK
deactivate "external1"
"internal1" -> "internal2": GET int2
activate "internal2"
"internal2" -> "external2": GET ext2
activate "external2"

"external2" -[#DarkGreen]> "internal2": <color:DarkGreen> 200 OK
deactivate "external2"
"internal2" -[#DarkGreen]> "internal1": <color:DarkGreen> 200 OK
deactivate "internal2"
"internal1" -[#DarkGreen]> "user": <color:DarkGreen> 200 OK
deactivate "internal1"
@enduml