
import groovy.json.JsonSlurper
import org.openapitools.generator.gradle.plugin.tasks.GenerateTask
import java.net.URI
import java.net.URL

description = "http4k typesafe HTTP contracts and OpenApi support"

plugins {
    id("org.http4k.community")
}

buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        mavenLocal()
    }

    dependencies {
        classpath(libs.openapi.generator.gradle.plugin)
    }
}

apply(plugin = "org.openapi.generator")

dependencies {
    api(project(":http4k-core"))
    api(project(":http4k-api-jsonschema"))
    api(project(":http4k-security-core"))

    implementation(libs.values4k)
    implementation(project(":http4k-security-oauth"))
    implementation(project(":http4k-format-jackson"))
    implementation(project(":http4k-multipart"))

    testImplementation(libs.values4k)
    testImplementation(project(":http4k-format-moshi"))
    testImplementation(project(":http4k-format-argo"))
    testImplementation(project(":http4k-format-kondor-json"))
    testImplementation(project(":http4k-testing-approval"))
    testImplementation(testFixtures(project(":http4k-core")))
    testImplementation(testFixtures(project(":http4k-security-oauth")))

    testFixturesApi(project(":http4k-format-jackson"))
    testFixturesImplementation(project(":http4k-testing-playwright"))
}

tasks {
        register<GenerateTask>("generateOpenApi3AutoClient") {
            generatorName = "kotlin"
            outputDir = file("${layout.buildDirectory.get().asFile.absolutePath}/generated/openapi/v3-auto")
            validateSpec = false
            inputSpec = file(
                "$projectDir/src/test/resources/org/http4k/contract/openapi/v3/OpenApi3AutoJacksonTest.renders as expected.approved"
            )
            inputs.file(inputSpec)
        }

        register<GenerateTask>("generateOpenApi3Client") {
            generatorName = "kotlin"
            outputDir = file("${layout.buildDirectory.get().asFile.absolutePath}/generated/openapi/v3")
            validateSpec = false
            inputSpec = file(
                "$projectDir/src/test/resources/org/http4k/contract/openapi/v3/OpenApi3AutoJacksonTest.renders as expected.approved"
            )
            inputs.file(inputSpec)
            mustRunAfter("generateOpenApi3AutoClient")
        }

        register<GenerateTask>("generateOpenApi2Client") {
            generatorName = "kotlin"
            outputDir = file("${layout.buildDirectory.get().asFile.absolutePath}/generated/openapi/v2")
            validateSpec = false
            inputSpec = file(
                "$projectDir/src/test/resources/org/http4k/contract/openapi/v2/OpenApi2Test.renders as expected.approved"
            )
            inputs.file(inputSpec)
            mustRunAfter("generateOpenApi3Client")
        }

        listOf(
            "compileKotlin",
            "compileTestKotlin",
            "processResources",
            "processTestResources",
            "dokkaGenerateModuleHtml",
        ).forEach {
            named(it).get().dependsOn(
                named("generateOpenApi3AutoClient").get(),
                named("generateOpenApi3Client").get(),
                named("generateOpenApi2Client").get()
            )
    }
}

val syncSwaggerUi = tasks.register("syncSwaggerUi") {
    description = "Generate SwaggerUiProps"

    val version = libs.versions.swagger.ui.get()
    val outputDir = layout.buildDirectory.dir("generated/sources/swaggerUi/kotlin")

    doLast {
        // Fetch metadata from jsDelivr which includes SRI hashes
        val apiUrl = "https://data.jsdelivr.com/v1/package/npm/swagger-ui-dist@$version"
        val data = JsonSlurper().parse(URI.create(apiUrl).toURL())

        val files = (data as? Map<*, *>)?.get("files") as? List<*>
            ?: throw GradleException("Could not find 'files' list in CDN response")

        fun findHash(name: String): String {
            val fileMeta = files
                .filterIsInstance<Map<*, *>>()
                .find { it["name"] == name } ?: throw GradleException("File $name not found in CDN")

            val hash = fileMeta["hash"] as String

            return when (hash.length) {
                44 -> "sha256-$hash"
                64 -> "sha384-$hash"
                88 -> "sha512-$hash"
                else -> hash // If it already has a prefix or is unknown
            }
        }

        val out = outputDir.get().asFile
        val pkgDir = out.resolve("org/http4k/contract/ui")
        pkgDir.mkdirs()

        pkgDir.resolve("SwaggerUiProps.kt").writeText(
            """package org.http4k.contract.ui
            |
            |/**
            | * Generated by Gradle from libs.versions.toml
            | */
            |object SwaggerUiProps {
            |    const val VERSION = "$version"
            |    const val BASE_URI = "https://cdn.jsdelivr.net/npm/swagger-ui@$version/dist"
            |    const val BUNDLE_HASH = "${findHash("swagger-ui-bundle.js")}"
            |    const val PRESET_HASH = "${findHash("swagger-ui-standalone-preset.js")}"
            |    const val CSS_HASH = "${findHash("swagger-ui.css")}"
            |}
            """.trimMargin()
        )
    }
}

configure<SourceSetContainer> {
    getByName("main").java.srcDir(layout.buildDirectory.dir("generated/sources/swaggerUi/kotlin"))
}

tasks.named("compileKotlin") {
    dependsOn(syncSwaggerUi)
}
