name: Build
on:
  push:
    branches:
    - master
    paths-ignore:
    - '**/*.md'
  pull_request:
    branches-ignore:
    - dependency-update
    paths-ignore:
    - '**/*.md'
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILDNOTE_API_KEY: ${{ secrets.BUILDNOTE_API_KEY }}
      BUILDNOTE_GITHUB_JOB_NAME: build
    permissions:
      checks: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        persist-credentials: false
        fetch-depth: 2
    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@ed408507eac070d1f99cc633dbcf757c94c7933a
    - name: Setup Java
      uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95
      with:
        java-version: '21'
        distribution: adopt
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92
    - name: Build
      timeout-minutes: 120
      run: bin/build_ci.sh
      env:
        HONEYCOMB_API_KEY: ${{ secrets.HONEYCOMB_API_KEY }}
        HONEYCOMB_DATASET: ${{ secrets.HONEYCOMB_DATASET }}
      shell: bash
    - name: Buildnote
      if: always()
      uses: buildnote/action@dccb92269d3f9a2515ad63e03d45af686ce3febd
    - name: Publish Test Report
      if: always()
      uses: mikepenz/action-junit-report@3585e9575db828022551b4231f165eb59a0e74e3
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        check_annotations: 'true'
        update_check: 'true'
    - name: Release (if required)
      if: github.ref == 'refs/heads/master'
      run: |-
        git config user.name github-actions
        git config user.email github-actions@github.com
        git remote set-url origin https://x-access-token:${{ secrets.ORG_PUBLIC_REPO_RELEASE_TRIGGERING }}@github.com/${GITHUB_REPOSITORY}.git
        bin/release_tag.sh
      env:
        GH_TOKEN: ${{ secrets.ORG_PUBLIC_REPO_RELEASE_TRIGGERING }}
      shell: bash