name: New Release - GitHub
on:
  repository_dispatch:
    types:
    - http4k-release
permissions:
  contents: read
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
    - name: Build release note
      run: bin/build_release_note.sh ${{ github.event.client_payload.version }} > NOTE.md
      shell: bash
    - name: Create Release
      uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.client_payload.version }}
        release_name: ${{ github.event.client_payload.version }}
        body_path: NOTE.md
        draft: false
        prerelease: false