name: OSSF scorecard
on:
  branch_protection_rule:
  workflow_dispatch:
  schedule:
  - cron: 0 8 * * 1
  push:
    branches:
    - master
permissions: read-all
jobs:
  analysis:
    runs-on: ubuntu-latest
    name: Scorecard analysis
    if: github.repository == 'http4k/http4k'
    permissions:
      id-token: write
      security-events: write
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        persist-credentials: false
    - name: Run analysis
      uses: ossf/scorecard-action@2d1146689b8cda280b9bc96326124645441f03bc
      with:
        results_file: results.sarif
        results_format: sarif
        publish_results: 'true'
    - name: Upload to code-scanning
      uses: github/codeql-action/upload-sarif@24c54180a607b1449ed407dd24f251e4e9147c8d
      with:
        sarif_file: results.sarif