name: Update Connect Website
on:
  push:
    branches:
      - master
    paths:
      - 'connect/src/**'
permissions:
  contents: read

jobs:
  release-site:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.12.4'
          architecture: 'x64'
      - run: pip install -r connect/requirements.txt
      - run: ./tools/embed_code.py
      - uses: actions/checkout@v4.2.2
        with:
          repository: http4k/www-http4k-connect
          path: tmp
          token: ${{ secrets.TOOLBOX_REPO_TOKEN }}
      - run: cp -R build/docs-website/docs tmp/
      - run: cp -R connect/src/mkdocs.yml tmp/
      - run: pushd tmp && mkdocs gh-deploy && popd

