name: "MCP Client Release"

on:
  repository_dispatch:
    types: [ release-mcp-client ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
        with:
          tag: ${{ github.event.client_payload.VERSION }}
          name: Release ${{ github.event.client_payload.VERSION }}
          body: |
            Release ${{ github.event.client_payload.VERSION }}
      - name: Write Upload URL To File
        run: |
          echo "${{steps.create_release.outputs.upload_url}}" > upload_url.txt
      - name: Publish Upload URL
        uses: actions/upload-artifact@v4.3.1
        with:
          name: upload_url.txt
          path: upload_url.txt

  release:
    needs: setup
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - macos-latest-xlarge
          - windows-latest
        include:
          - os: macos-latest
            label: macos-x86_64
            suffix: ""
          - os: macos-latest-xlarge
            label: macos-arm64
            suffix: ""
          - os: windows-latest
            label: windows
            suffix: ".exe"
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: "21"
          distribution: "graalvm"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "22.3.0"
      - name: Build
        run: ./gradlew -PVERSION="${{ github.event.client_payload.VERSION }}" :http4k-mcp-desktop:nativeCompile
      - name: Get Release URL
        uses: actions/download-artifact@v4.1.9
        with:
          name: upload_url.txt
      - name: Get Upload URL
        run: |
          echo "UPLOAD_URL=$(cat upload_url.txt)" >> $GITHUB_ENV
      - name: Release ${{matrix.label}} Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
        with:
          upload_url: ${{env.UPLOAD_URL}}
          asset_name: mcp-desktop-${{ github.event.client_payload.VERSION }}-${{matrix.label}}
          asset_path: pro/mcp/desktop/build/native/nativeCompile/mcp-desktop
          asset_content_type: application/octet-stream
