name: Security - Dependency Analysis (dependabot)
on:
  push:
    branches:
    - master
    paths-ignore:
    - '**/*.md'
  schedule:
  - cron: 0 12 * * 3
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    name: Dependencies
    if: github.repository == 'http4k/http4k'
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
    - name: Setup Java
      uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95
      with:
        java-version: '21'
        distribution: adopt
    - name: Generate and save dependency graph
      uses: gradle/actions/dependency-submission@ed408507eac070d1f99cc633dbcf757c94c7933a