name: Server Shutdown Tests
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**/*.md'
jobs:
  run_tests:
    name: Run Shutdown Tests
    runs-on: ubuntu-latest
    env:
      BUILDNOTE_API_KEY: ${{ secrets.BUILDNOTE_API_KEY }}
      BUILDNOTE_GITHUB_JOB_NAME: run_tests
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-java@v4.7.0
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        timeout-minutes: 25
        run: bin/run_shutdown_tests.sh
        env:
          SERVER_HOST: localhost
          HONEYCOMB_API_KEY: ${{ secrets.HONEYCOMB_API_KEY }}
          HONEYCOMB_DATASET: ${{ secrets.HONEYCOMB_DATASET }}
      - name: Buildnote
        uses: buildnote/action@main
        if: always()


