name: Server Shutdown Tests
on:
  push:
    branches:
    - master
    paths-ignore:
    - '**/*.md'
permissions:
  contents: read
jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: Run Shutdown Tests
    env:
      BUILDNOTE_API_KEY: ${{ secrets.BUILDNOTE_API_KEY }}
      BUILDNOTE_GITHUB_JOB_NAME: run_tests
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
    - name: Setup Java
      uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95
      with:
        java-version: '21'
        distribution: adopt
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92
    - name: Build
      timeout-minutes: 25
      run: bin/run_shutdown_tests.sh
      env:
        SERVER_HOST: localhost
        HONEYCOMB_API_KEY: ${{ secrets.HONEYCOMB_API_KEY }}
        HONEYCOMB_DATASET: ${{ secrets.HONEYCOMB_DATASET }}
      shell: bash
    - name: Buildnote
      if: always()
      uses: buildnote/action@dccb92269d3f9a2515ad63e03d45af686ce3febd